### ISSUE TITLE
VMware AirWatch Admin Assistant CodeSignatureVerifier issues

### ISSUE THREAD

**Issue by flammable** [autopkg/n8felton-recipes#121]
Hey Nate -

I ran my override for VMwareAirWatchAdminAssistant.munki.recipe this morning, and received this output:

```
$ autopkg run -v local.munki.VMwareAirWatchAdminAssistant
Processing local.munki.VMwareAirWatchAdminAssistant...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.0.0
SparkleUpdateInfoProvider: Found URL https://getwsone.com/AdminAssistant/VMwareWorkspaceONEAdminAssistant.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Fri, 20 Dec 2019 18:37:20 GMT
URLDownloader: Storing new ETag header: "1f9759d-59a26f7d38ea8"
URLDownloader: Downloaded /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/downloads/VMwareAirWatchAdminAssistant-2.0.0.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/downloads/VMwareAirWatchAdminAssistant-2.0.0.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 298, in main
    f"Error processing path '{input_path}' with glob. "
autopkglib.ProcessorError: Error processing path '/private/tmp/dmg.h8jXeH/VMware AirWatch Admin Assistant.pkg' with glob. 
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
Error processing path '/private/tmp/dmg.h8jXeH/VMware AirWatch Admin Assistant.pkg' with glob. 
Failed.
Receipt written to /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/receipts/local.munki-receipt-20200401-084133.plist

The following recipes failed:
    local.munki.VMwareAirWatchAdminAssistant
        Error in local.munki.VMwareAirWatchAdminAssistant: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.h8jXeH/VMware AirWatch Admin Assistant.pkg' with glob. 

The following new items were downloaded:
    Download Path                                                                                                                    
    -------------                                                                                                                    
    /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/downloads/VMwareAirWatchAdminAssistant-2.0.0.dmg
```

Any idea what's up? My AutoPkg Mac is still running macOS 10.13 (I'm replacing it soon), but I'm not sure if that's related.

Thanks!

Mike

**Comment by cwhits** [comment]
the pkg name changed.

From the recipe:
```
<key>input_path</key>
<string>%pathname%/VMware AirWatch Admin Assistant.pkg</string>
```

from the dmg:
`VMware Workspace ONE Admin Assistant.pkg`

We can get this fixed up today. If you want to submit a PR though we can accept it today too.

**Comment by flammable** [comment]
Thanks, Chris!

**Comment by flammable** [comment]
Hmm, I tried again and got a different error:

```
$ autopkg run -v local.munki.VMwareAirWatchAdminAssistant
Processing local.munki.VMwareAirWatchAdminAssistant...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 2.0.0
SparkleUpdateInfoProvider: Found URL https://getwsone.com/AdminAssistant/VMwareWorkspaceONEAdminAssistant.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/downloads/VMwareAirWatchAdminAssistant-2.0.0.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/downloads/VMwareAirWatchAdminAssistant-2.0.0.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "VMware Workspace ONE Admin Assistant.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Wandering WiFi LLC (S2ZMFGQM93)
CodeSignatureVerifier:        SHA1 fingerprint: 68 55 47 4B C3 B9 57 BA A2 80 F7 72 27 62 7D 41 BE DB CE 26
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: Wandering WiFi LLC -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: Wandering WiFi LLC (S2ZMFGQM93) -> Developer ID Certification Authority -> Apple Root CA
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 324, in main
    self.process_installer_package(matched_input_path)
  File "/Library/AutoPkg/autopkglib/CodeSignatureVerifier.py", line 275, in process_installer_package
    "Mismatch in authority names. Note that all "
autopkglib.ProcessorError: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
Receipt written to /Users/macadmin/Library/AutoPkg/Cache/local.munki.VMwareAirWatchAdminAssistant/receipts/local.munki-receipt-20200401-204457.plist

The following recipes failed:
    local.munki.VMwareAirWatchAdminAssistant
        Error in local.munki.VMwareAirWatchAdminAssistant: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Nothing downloaded, packaged or imported.
```

I'll try updating the code signature to see if the recipe works properly after that. If it does, I'll send a pull request!

Also: would it be worth renaming the recipe, since the product is called Workspace ONE, not AirWatch, anymore?

**Comment by flammable** [comment]
I submitted PR #122 to fix that.

The pkg itself doesn't install with Munki, but I think that's due to TCC restrictions (there's a preinstall script that triggers a dialog about accessing your Documents folder).
